apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-php-app
  namespace: team1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-php-app
  template:
    metadata:
      labels:
        app: my-php-app
    spec:
      containers:
      - name: my-php-app
        image: fredriksacr.azurecr.io/my-php-app:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
